apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickerdataappapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tickerdataappapi
  template:
    metadata:
      labels:
        app: tickerdataappapi
    spec:
      containers:
        - name: tickerdataappapi
          image: tickeracr.azurecr.io/companytickerdataappapi:v9
          env:
            - name: StoreSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
          - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: tickerdataappapi-service
spec:
  type: LoadBalancer
  selector:
    app: tickerdataappapi
  ports:
  - protocol: TCP
    port: 80
