version: '3.4'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017


  company.tickerdataapp.api:
    image: ${DOCKER_REGISTRY-}companytickerdataappapi
    build:
      context: .
      dockerfile: Company.TickerDataApp.Api/Dockerfile
    ports:
        - 80:80
    environment:
      StoreSettings__ConnectionString: mongodb://mongo:27017
    depends_on:
      - mongo