apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickerdataappapi-deployment
spec:
  selector:
    matchLabels:
      app: tickerdataappapi
  template:
    metadata:
      labels:
        app: tickerdataappapi
    spec:
      containers:
      - name: tickerdataappapi
        image: vladimirmit/companytickerdataappapi:latest
        env:
          - name: StoreSettings__ConnectionString
            valueFrom:
              configMapKeyRef:
                name: mongo-configmap
                key: connection_string
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tickerdataappapi-service
spec:
  type: NodePort
  selector:
    app: tickerdataappapi
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 31000
